// dashboard/src/app/features/auth/login/login.component.ts
import { CommonModule } from '@angular/common';
import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { finalize } from 'rxjs';
import { AuthStateService } from '../../../core/services/auth-state.service';
import { resolveErrorMessage } from '../../../core/utils/formatters';
import { AuthLayoutComponent } from '../../../shared/components/auth-layout/auth-layout.component';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink, AuthLayoutComponent],
  template: `
    <app-auth-layout
      title="Entrar"
      subtitle="Acesse seu painel financeiro"
    >
      <form class="space-y-4" (ngSubmit)="submit()">
        <input
          type="text"
          placeholder="Usuário"
          [(ngModel)]="username"
          name="username"
          class="w-full rounded-xl border border-slate-200 px-3 py-3 text-slate-900 outline-none focus:border-blue-500"
        />

        <input
          type="password"
          placeholder="Senha"
          [(ngModel)]="password"
          name="password"
          class="w-full rounded-xl border border-slate-200 px-3 py-3 text-slate-900 outline-none focus:border-blue-500"
        />

        <p *ngIf="error" class="text-sm text-red-600">{{ error }}</p>

        <button
          type="submit"
          [disabled]="loading"
          class="w-full cursor-pointer rounded-xl bg-blue-600 py-3 font-bold text-white transition-colors hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-70"
        >
          {{ loading ? 'Entrando...' : 'Entrar' }}
        </button>

        <a
          routerLink="/register"
          class="block w-full text-center text-blue-600 transition-colors hover:text-blue-700"
        >
          Criar conta
        </a>
      </form>
    </app-auth-layout>
  `,
})
export class LoginComponent {
  private readonly auth = inject(AuthStateService);
  private readonly router = inject(Router);

  username = '';
  password = '';
  error: string | null = null;
  loading = false;

  submit(): void {
    this.error = null;

    if (!this.username.trim()) {
      this.error = 'Informe seu usuário.';
      return;
    }

    if (!this.password.trim()) {
      this.error = 'Informe sua senha.';
      return;
    }

    this.loading = true;

    this.auth
      .login({ usuario: this.username.trim(), senha: this.password })
      .pipe(finalize(() => (this.loading = false)))
      .subscribe({
        next: () => this.router.navigateByUrl('/'),
        error: (err) =>
          (this.error = resolveErrorMessage(err, 'Erro ao realizar login.')),
      });
  }
}

// mobile/app/(auth)/login.tsx
import { Link, useRouter } from 'expo-router';
import { useState } from 'react';
import { StyleSheet, Text } from 'react-native';

import { AuthLayout } from '@/components/ui/auth-layout';
import { Button } from '@/components/ui/button';
import { InputField } from '@/components/ui/input-field';
import { AppColors } from '@/constants/app-theme';
import { useAuth } from '@/contexts/auth-context';
import { resolveErrorMessage } from '@/core/utils/formatters';

export default function LoginScreen() {
  const { login } = useAuth();
  const router = useRouter();

  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  async function submit() {
    setError(null);

    if (!username.trim()) {
      setError('Informe seu usuário.');
      return;
    }

    if (!password.trim()) {
      setError('Informe sua senha.');
      return;
    }

    setLoading(true);

    try {
      await login({ usuario: username.trim(), senha: password });
      router.replace('/(app)');
    } catch (err) {
      setError(resolveErrorMessage(err, 'Erro ao realizar login.'));
    } finally {
      setLoading(false);
    }
  }

  return (
    <AuthLayout title="Entrar" subtitle="Acesse seu painel financeiro">
      <InputField
        placeholder="Usuário"
        autoCapitalize="none"
        value={username}
        onChangeText={setUsername}
      />
      <InputField
        placeholder="Senha"
        secureTextEntry
        value={password}
        onChangeText={setPassword}
      />

      {error ? <Text style={styles.error}>{error}</Text> : null}

      <Button title={loading ? 'Entrando...' : 'Entrar'} loading={loading} onPress={submit} />

      <Link href="/(auth)/register" asChild>
        <Button title="Criar conta" variant="link" />
      </Link>
    </AuthLayout>
  );
}

const styles = StyleSheet.create({
  error: {
    color: AppColors.error,
    fontSize: 14,
  },
});
