// web/src/components/layout/AppLayout.tsx
import { NavLink, Outlet, useLocation } from 'react-router-dom'
import { useAuth } from '../../context/AuthContext'

const navItems = [
  { to: '/', label: 'Dashboard', end: true },
  { to: '/contas', label: 'Contas', end: false },
  { to: '/transacoes', label: 'Transações', end: false },
  { to: '/categorias', label: 'Categorias', end: false },
]

const pageTitles: Record<string, string> = {
  '/': 'Dashboard',
  '/contas': 'Contas',
  '/transacoes': 'Transações',
  '/categorias': 'Categorias',
}

export function AppLayout() {
  const { name, username, logout } = useAuth()
  const location = useLocation()
  const displayName = name ?? username ?? 'Usuário'
  const pageTitle = pageTitles[location.pathname] ?? 'Dashboard'

  return (
    <div className="flex min-h-svh bg-[#f5f7fb]">
      <aside className="flex w-[248px] min-w-[248px] max-w-[248px] flex-col justify-between bg-[#172033] px-4 py-6">
        <div className="space-y-7">
          <div className="px-2">
            <h1 className="text-xl font-bold text-white">TechFinance</h1>
            <p className="text-xs text-[#9da8ba]">Controle financeiro pessoal</p>
          </div>

          <nav className="space-y-2">
            {navItems.map((item) => (
              <NavLink
                key={item.to}
                to={item.to}
                end={item.end}
                className={({ isActive }) =>
                  [
                    'block w-full rounded-lg px-3.5 py-3 text-left text-sm transition-colors',
                    isActive
                      ? 'bg-[#2f6fed] font-medium text-white'
                      : 'text-[#c7d0df] hover:bg-[#22304a] hover:text-white',
                  ].join(' ')
                }
              >
                {item.label}
              </NavLink>
            ))}
          </nav>
        </div>

        <div className="space-y-1 rounded-[10px] bg-[#202c43] p-3">
          <p className="font-bold text-white">{displayName}</p>
          <p className="text-xs text-[#9da8ba]">Usuário logado</p>
          <button
            type="button"
            onClick={logout}
            className="mt-1 cursor-pointer text-sm text-[#c7d0df] transition-colors hover:text-white"
          >
            Sair
          </button>
        </div>
      </aside>

      <div className="flex min-w-0 flex-1 flex-col">
        <header className="flex h-16 items-center border-b border-[#e4e8ef] bg-white px-6">
          <h2 className="text-lg font-bold text-[#172033]">{pageTitle}</h2>
        </header>

        <main className="flex-1 overflow-auto p-6">
          <Outlet />
        </main>
      </div>
    </div>
  )
}

// dashboard/src/app/layout/app-layout/app-layout.component.ts
import { CommonModule } from '@angular/common';
import { Component, inject } from '@angular/core';
import { Router, RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';
import { AuthStateService } from '../../core/services/auth-state.service';

const NAV_ITEMS = [
  { to: '/', label: 'Dashboard', exact: true },
  { to: '/contas', label: 'Contas', exact: false },
  { to: '/transacoes', label: 'Transações', exact: false },
  { to: '/categorias', label: 'Categorias', exact: false },
];

const PAGE_TITLES: Record<string, string> = {
  '/': 'Dashboard',
  '/contas': 'Contas',
  '/transacoes': 'Transações',
  '/categorias': 'Categorias',
};

@Component({
  selector: 'app-layout',
  standalone: true,
  imports: [CommonModule, RouterOutlet, RouterLink, RouterLinkActive],
  template: `
    <div class="flex min-h-svh bg-[#f5f7fb]">
      <aside
        class="flex w-[248px] min-w-[248px] max-w-[248px] flex-col justify-between bg-[#172033] px-4 py-6"
      >
        <div class="space-y-7">
          <div class="px-2">
            <h1 class="text-xl font-bold text-white">TechFinance</h1>
            <p class="text-xs text-[#9da8ba]">Controle financeiro pessoal</p>
          </div>

          <nav class="space-y-2">
            <a
              *ngFor="let item of navItems"
              [routerLink]="item.to"
              routerLinkActive="bg-[#2f6fed] font-medium text-white"
              [routerLinkActiveOptions]="{ exact: item.exact }"
              class="block w-full rounded-lg px-3.5 py-3 text-left text-sm text-[#c7d0df] transition-colors hover:bg-[#22304a] hover:text-white"
            >
              {{ item.label }}
            </a>
          </nav>
        </div>

        <div class="space-y-1 rounded-[10px] bg-[#202c43] p-3">
          <p class="font-bold text-white">{{ displayName }}</p>
          <p class="text-xs text-[#9da8ba]">Usuário logado</p>
          <button
            type="button"
            (click)="logout()"
            class="mt-1 cursor-pointer text-sm text-[#c7d0df] transition-colors hover:text-white"
          >
            Sair
          </button>
        </div>
      </aside>

      <div class="flex min-w-0 flex-1 flex-col">
        <header
          class="flex h-16 items-center border-b border-[#e4e8ef] bg-white px-6"
        >
          <h2 class="text-lg font-bold text-[#172033]">{{ pageTitle }}</h2>
        </header>

        <main class="flex-1 overflow-auto p-6">
          <router-outlet (activate)="onActivate()"></router-outlet>
        </main>
      </div>
    </div>
  `,
})
export class AppLayoutComponent {
  private readonly auth = inject(AuthStateService);
  private readonly router = inject(Router);

  readonly navItems = NAV_ITEMS;
  pageTitle = 'Dashboard';

  get displayName(): string {
    return this.auth.name ?? this.auth.username ?? 'Usuário';
  }

  logout(): void {
    this.auth.logout();
    void this.router.navigateByUrl('/login');
  }

  onActivate(): void {
    const path = window.location.pathname;
    this.pageTitle = PAGE_TITLES[path] ?? 'Dashboard';
  }
}
